inputs:
  # string: path to data
  datadir:
  # string: path to output directory
  outdir:
  # string: path to target list
  targets:

parameters:
  # string: instrument
  instrument:
  # string: filetype
  filetype:
  # int: minimum number for velocity window in km/s
  vel_min:
  # int: maximum number for velocity window in km/s
  vel_max:
  # string: grating
  grating:
  # will need to deal with situations where there are no gratings in the future

defaults:
  continuum_left: [-450, -300]
  continuum_right: [300, 450]
  all_ions: